[package]
name = "project_euler"
version = "0.1.0"
authors = ["Barnabas Forgo <speedo@devo.hu>"]
edition = "2018"

[lib]
path = "src/lib/mod.rs"

[dependencies]
num = "0.2.0"

[dependencies.auto_test]
path = "auto_test"

[dependencies.submitter]
path = "submitter"
